// Generated by `bun init`
// Enhanced type declarations for the project

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: string;
  export default path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module "*.css" {
  /**
   * CSS file import
   */
  const css: string;
  export default css;
}

declare module "*.png" {
  /**
   * PNG image import
   */
  const path: string;
  export default path;
}

declare module "*.jpg" {
  /**
   * JPG image import
   */
  const path: string;
  export default path;
}

declare module "*.jpeg" {
  /**
   * JPEG image import
   */
  const path: string;
  export default path;
}

declare module "*.gif" {
  /**
   * GIF image import
   */
  const path: string;
  export default path;
}

declare module "*.webp" {
  /**
   * WebP image import
   */
  const path: string;
  export default path;
}

declare module "*.ico" {
  /**
   * ICO image import
   */
  const path: string;
  export default path;
}

declare module "*.json" {
  /**
   * JSON file import with proper typing
   */
  const value: any;
  export default value;
}

// Global environment variable types
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NODE_ENV?: 'development' | 'production' | 'test';
      [key: string]: string | undefined;
    }
  }
}

export {};
