packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@descope/nextjs-sdk": ^0.15.3
  "@eslint/js": ^9.38.0
  "@tailwindcss/postcss": ^4.1.16
  "@tailwindcss/vite": ^4.1.16
  "@tanstack/react-form": ^1.23.8
  "@tanstack/react-query": ^5.90.8
  "@trpc/client": ^11.7.1
  "@trpc/server": ^11.8.0
  "@trpc/tanstack-react-query": ^11.7.1
  "@types/node": ^22.18.12
  "@vitejs/plugin-react": 5.1.0
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12
  vite: 7.1.12
  vitest: ^3.2.4

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.4
    react-dom: 19.1.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  # Pin drizzle-orm to prevent multiple versions from different peer dependency resolutions
  # which causes "Types have separate declarations of a private property" errors
  drizzle-orm: 0.44.7
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
